<?php
    $libros = array(
      array("isbn" => "0183jsk83", "titulo" => "Titulo 1", "descripcion" => "Descripcion 1",
      "categoria" => "novela negra", "editorial" => "Editorial A", "img" => "./img/cr1.jfif", "precio" => 100),
      array("isbn" => "01823sk83", "titulo" => "Titulo 2", "descripcion" => "Descripcion 2",
      "categoria" => "novela negra", "editorial" => "Editorial B", "img" => "./img/cr2.jfif", "precio" => 100),
      array("isbn" => "0183jsk53", "titulo" => "Titulo 3", "descripcion" => "Descripcion 3",
      "categoria" => "novela negra", "editorial" => "Editorial C", "img" => "./img/cr3.png", "precio" => 100),
      array("isbn" => "0183j5DS3", "titulo" => "Titulo 4", "descripcion" => "Descripcion 4",
      "categoria" => "novela romantica", "editorial" => "Editorial A", "img" => "./img/cr4.jfif", "precio" => 100),
      array("isbn" => "018gtsk83", "titulo" => "Titulo 5", "descripcion" => "Descripcion 5",
      "categoria" => "novela romantica", "editorial" => "Editorial B", "img" => "./img/cr5.jfif", "precio" => 100),
      array("isbn" => "0123jsk83", "titulo" => "Titulo 6", "descripcion" => "Descripcion 6",
      "categoria" => "novela romantica", "editorial" => "Editorial C", "img" => "./img/cr6.jfif", "precio" => 100),
      array("isbn" => "01gtjsk83", "titulo" => "Titulo 7", "descripcion" => "Descripcion 7",
      "categoria" => "historia", "editorial" => "Editorial A", "img" => "./img/cr7.jfif", "precio" => 100),
      array("isbn" => "018367k83", "titulo" => "Titulo 8", "descripcion" => "Descripcion 8",
      "categoria" => "historia", "editorial" => "Editorial B", "img" => "./img/cr8.jfif", "precio" => 100),
      array("isbn" => "0183bs683", "titulo" => "Titulo 9", "descripcion" => "Descripcion 9",
      "categoria" => "historia", "editorial" => "Editorial C", "img" => "./img/cr9.jfif", "precio" => 100),
      array("isbn" => "0183jsfg3", "titulo" => "Titulo 10", "descripcion" => "Descripcion 10",
      "categoria" => "ciencias", "editorial" => "Editorial A", "img" => "./img/cr10.jfif", "precio" => 100),
      array("isbn" => "0183js122", "titulo" => "Titulo 11", "descripcion" => "Descripcion 11",
      "categoria" => "ciencias", "editorial" => "Editorial B", "img" => "./img/cr1.jfif", "precio" => 100),
      array("isbn" => "0183js75g", "titulo" => "Titulo 12", "descripcion" => "Descripcion 12",
      "categoria" => "ciencias", "editorial" => "Editorial C", "img" => "./img/cr2.jfif", "precio" => 100),
      array("isbn" => "01843g3fd", "titulo" => "Titulo 13", "descripcion" => "Descripcion 13",
      "categoria" => "deporte", "editorial" => "Editorial A", "img" => "./img/cr3.png", "precio" => 100),
      array("isbn" => "01g4zsk83", "titulo" => "Titulo 14", "descripcion" => "Descripcion 14",
      "categoria" => "deporte", "editorial" => "Editorial B", "img" => "./img/cr4.jfif", "precio" => 100),
      array("isbn" => "018z3sk83", "titulo" => "Titulo 15", "descripcion" => "Descripcion 15",
      "categoria" => "deporte", "editorial" => "Editorial C", "img" => "./img/cr5.jfif", "precio" => 100),
      array("isbn" => "3443jsk83", "titulo" => "Titulo 16", "descripcion" => "Descripcion 16",
      "categoria" => "cocina", "editorial" => "Editorial A", "img" => "./img/cr6.jfif", "precio" => 100),
      array("isbn" => "iii3jsk83", "titulo" => "Titulo 17", "descripcion" => "Descripcion 17",
      "categoria" => "cocina", "editorial" => "Editorial B", "img" => "./img/cr7.jfif", "precio" => 100),
      array("isbn" => "018y6sk83", "titulo" => "Titulo 18", "descripcion" => "Descripcion 18",
      "categoria" => "cocina", "editorial" => "Editorial C", "img" => "./img/cr8.jfif", "precio" => 100),
      array("isbn" => "018376k83", "titulo" => "Titulo 19", "descripcion" => "Descripcion 19",
      "categoria" => "sci-fi", "editorial" => "Editorial A", "img" => "./img/cr9.jfif", "precio" => 100),
      array("isbn" => "0183j5433", "titulo" => "Titulo 20", "descripcion" => "Descripcion 20",
      "categoria" => "sci-fi", "editorial" => "Editorial B", "img" => "./img/cr10.jfif", "precio" => 100),
      array("isbn" => "0183js653", "titulo" => "Titulo 21", "descripcion" => "Descripcion 21",
      "categoria" => "sci-fi", "editorial" => "Editorial C", "img" => "./img/cr1.jfif", "precio" => 100),
    );

    $categorias = array_unique(array_column($libros, 'categoria'));

?>